targets:
  $default:
    builders:
      # json_serializable:
      #   options:
      #     explicit_to_json: true
      #     include_if_null: false
      #     create_field_map: false
      #     checked: false
      freezed:
        options:
          when: false
          map: false